//
//  ClockFaceKit.h
//  ClickKit
//
//  Created by Paul Wood on 11/8/14.
//  Copyright (c) 2014 paulwoodiii.com. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ClockFaceKit : NSObject

// Drawing Methods
+ (void)drawClock1;
+ (void)drawMinFace;
+ (void)drawComposed;
+ (void)drawMinHand;
+ (void)drawHrHand;
+ (void)drawHoursText;
+ (void)drawHoursNotches;
+ (void)drawDial;
+ (void)drawMinuteNotchSingle;
+ (void)drawMinuteNotches;
+ (void)drawRim;

@end
